# Generated by Django 5.0.1 on 2024-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='country',
            field=models.CharField(default='<empty>', max_length=200),
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.CharField(default='<empty>', max_length=1000),
        ),
        migrations.AddField(
            model_name='gym',
            name='post_code',
            field=models.CharField(default='<empty>', max_length=20),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(default='<empty>', max_length=1000),
        ),
    ]
