# Generated by Django 5.0.1 on 2024-01-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_gym_country_gym_description_gym_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 16, 20, 19, 167647), verbose_name='date published'),
        ),
    ]
