# Generated by Django 5.0.1 on 2024-01-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_gym_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='pub_date',
        ),
    ]
