# Generated by Django 5.0.1 on 2024-01-14 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_gym_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
